# Generated by Django 6.0.1 on 2026-02-02 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("gender", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=100)),
                ("occupation", models.CharField(max_length=100)),
                (
                    "self_employed",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("family_history", models.CharField(max_length=50)),
                ("days_indoors", models.CharField(max_length=50)),
                ("growing_stress", models.CharField(max_length=50)),
                ("changes_habits", models.CharField(max_length=50)),
                ("mental_health_history", models.CharField(max_length=50)),
                ("mood_swings", models.CharField(max_length=50)),
                ("coping_struggles", models.CharField(max_length=50)),
                ("work_interest", models.CharField(max_length=50)),
                ("social_weakness", models.CharField(max_length=50)),
                ("mental_health_interview", models.CharField(max_length=50)),
                ("care_options", models.CharField(max_length=50)),
                ("prediction", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
