# Generated by Django 6.0.1 on 2026-02-02 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="treatment",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Sí"), ("No", "No")],
                max_length=50,
                null=True,
                verbose_name="Tratamiento Previo",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="care_options",
            field=models.CharField(
                choices=[("Not sure", "No estoy seguro"), ("No", "No"), ("Yes", "Sí")],
                max_length=50,
                verbose_name="Opciones de Cuidado",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="changes_habits",
            field=models.CharField(
                choices=[("Yes", "Sí"), ("No", "No"), ("Maybe", "Tal vez")],
                max_length=50,
                verbose_name="Cambios de Hábitos",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="coping_struggles",
            field=models.CharField(
                choices=[("Yes", "Sí"), ("No", "No")],
                max_length=50,
                verbose_name="Dificultad para Afrontar Problemas",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="country",
            field=models.CharField(
                choices=[
                    ("United States", "Estados Unidos"),
                    ("Poland", "Polonia"),
                    ("Australia", "Australia"),
                    ("Canada", "Canadá"),
                    ("United Kingdom", "Reino Unido"),
                    ("South Africa", "Sudáfrica"),
                    ("Sweden", "Suecia"),
                    ("New Zealand", "Nueva Zelanda"),
                    ("Netherlands", "Países Bajos"),
                    ("India", "India"),
                    ("Belgium", "Bélgica"),
                    ("Ireland", "Irlanda"),
                    ("France", "Francia"),
                    ("Portugal", "Portugal"),
                    ("Brazil", "Brasil"),
                    ("Costa Rica", "Costa Rica"),
                    ("Russia", "Rusia"),
                    ("Germany", "Alemania"),
                    ("Switzerland", "Suiza"),
                    ("Finland", "Finlandia"),
                    ("Israel", "Israel"),
                    ("Italy", "Italia"),
                    ("Bosnia and Herzegovina", "Bosnia y Herzegovina"),
                    ("Singapore", "Singapur"),
                    ("Nigeria", "Nigeria"),
                    ("Croatia", "Croacia"),
                    ("Thailand", "Tailandia"),
                    ("Denmark", "Dinamarca"),
                    ("Mexico", "México"),
                    ("Greece", "Grecia"),
                    ("Moldova", "Moldavia"),
                    ("Colombia", "Colombia"),
                    ("Georgia", "Georgia"),
                    ("Czech Republic", "República Checa"),
                    ("Philippines", "Filipinas"),
                ],
                max_length=100,
                verbose_name="País",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="days_indoors",
            field=models.CharField(
                choices=[
                    ("1-14 days", "1-14 días"),
                    ("Go out Every day", "Salgo todos los días"),
                    ("More than 2 months", "Más de 2 meses"),
                    ("15-30 days", "15-30 días"),
                    ("31-60 days", "31-60 días"),
                ],
                max_length=50,
                verbose_name="Días en Casa",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="family_history",
            field=models.CharField(
                choices=[("Yes", "Sí"), ("No", "No")],
                max_length=50,
                verbose_name="Historial Familiar",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="gender",
            field=models.CharField(
                choices=[("Female", "Mujer"), ("Male", "Hombre")],
                max_length=50,
                verbose_name="Género",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="growing_stress",
            field=models.CharField(
                choices=[("Yes", "Sí"), ("No", "No"), ("Maybe", "Tal vez")],
                max_length=50,
                verbose_name="Aumento de Estrés",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="mental_health_history",
            field=models.CharField(
                choices=[("Yes", "Sí"), ("No", "No"), ("Maybe", "Tal vez")],
                max_length=50,
                verbose_name="Historial de Salud Mental",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="mental_health_interview",
            field=models.CharField(
                choices=[("Yes", "Sí"), ("No", "No"), ("Maybe", "Tal vez")],
                max_length=50,
                verbose_name="Entrevista sobre Salud Mental",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="mood_swings",
            field=models.CharField(
                choices=[("Medium", "Medio"), ("Low", "Bajo"), ("High", "Alto")],
                max_length=50,
                verbose_name="Cambios de Humor",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("Corporate", "Corporativo"),
                    ("Student", "Estudiante"),
                    ("Business", "Negocios"),
                    ("Housewife", "Ama de casa"),
                    ("Others", "Otros"),
                ],
                max_length=100,
                verbose_name="Ocupación",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="prediction",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Predicción"
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="self_employed",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Sí"), ("No", "No")],
                max_length=50,
                null=True,
                verbose_name="Autónomo",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="social_weakness",
            field=models.CharField(
                choices=[("Yes", "Sí"), ("No", "No"), ("Maybe", "Tal vez")],
                max_length=50,
                verbose_name="Debilidad Social",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="work_interest",
            field=models.CharField(
                choices=[("Yes", "Sí"), ("No", "No"), ("Maybe", "Tal vez")],
                max_length=50,
                verbose_name="Interés en el Trabajo",
            ),
        ),
    ]
